#!/bin/sh /etc/rc.common
#
# Copyright (C) 2017 scsz <lijun00326@gmail.com>
#
# This is free software, licensed under the GNU Affero General Public License v3.0
# See /LICENSE for more information.
#
#

START=99
STOP=99

start() {
    python -u /lib/jlu-drcom/daemon.py >/tmp/drdaemon.log &
}

stop() {
    kill -s 9 `pgrep -f newclient.py`
    kill -s 9 `pgrep -f daemon.py`
}